title: Spin Echo
pulseSeq:

    - t: 0
      FA: 90
      B1: 'RF/rect.yml'
      dur: 0.5 # [ms]
    - t: 10
      FA: 1
      B1: 'RF/bsse.yml'
      dur: 7.064 # [ms]
    - t: 30
      FA: 90
      B1: 'RF/rect.yml'
      dur: 0.5 # [ms]
      phase: 90
    - t: 40
      FA: 1
      B1: 'RF/bsse.yml'
      dur: 7.064 # [ms]
TR: 80
B0: 1.5
components:
    - T1: 790.0
      T2: 92.0
nIsochromats: 20
isochromatStep: 0.01
speed: 0.01
output: 
  - type: 3D
    file: BSSE_3D.gif
  - type: psd
    file: BSSE_psd.gif